/**
 * CSS Generator
 *
 * Generates CSS classes from shadow presets.
 * Used both at build time and can be used at runtime.
 */

import { buildShadow, toBoxShadow, toDropShadow } from "./factory"
import type { ShadowPreset } from "./presets/effective"

/**
 * Options for CSS generation.
 */
export interface GenerateCSSOptions {
  /** Prefix for class names (default: "") */
  prefix?: string
  /** Include box-shadow classes (default: true) */
  boxShadow?: boolean
  /** Include drop-shadow classes (default: true) */
  dropShadow?: boolean
  /** CSS selector format: "class" or "css-variable" (default: "class") */
  format?: "class" | "css-variable"
}

/**
 * Generated shadow values for one elevation level.
 */
export interface GeneratedShadow {
  level: number
  boxShadow: string
  dropShadow: string
}

/**
 * Generates shadow values from a preset.
 *
 * @param preset - Shadow preset configuration
 * @returns Array of generated shadow strings per elevation
 */
export function generateFromPreset(preset: ShadowPreset): GeneratedShadow[] {
  return preset.elevations.map((elevation, level) => {
    const config = { ...preset.base, ...elevation }

    // Level 0 is always "none"
    if (level === 0 || config.finalAlpha === 0) {
      return {
        level,
        boxShadow: "none",
        dropShadow: "none"
      }
    }

    const shadowSet = buildShadow(config)
    return {
      level,
      boxShadow: toBoxShadow(shadowSet),
      dropShadow: toDropShadow(shadowSet)
    }
  })
}

/**
 * Generates CSS string from a preset.
 *
 * @param preset - Shadow preset configuration
 * @param options - Generation options
 * @returns CSS string with class definitions
 */
export function generateCSS(
  preset: ShadowPreset,
  options: GenerateCSSOptions = {}
): string {
  const {
    prefix = "",
    boxShadow: includeBoxShadow = true,
    dropShadow: includeDropShadow = true,
    format = "class"
  } = options

  const shadows = generateFromPreset(preset)
  const lines: string[] = []

  // Header comment
  lines.push(`/**`)
  lines.push(` * ${preset.name} Shadow Preset`)
  lines.push(` * ${preset.description}`)
  lines.push(` *`)
  lines.push(` * Generated by @effective/shadow`)
  lines.push(` */`)
  lines.push(``)

  if (format === "css-variable") {
    // CSS Custom Properties format
    lines.push(`:root {`)

    if (includeBoxShadow) {
      shadows.forEach(({ level, boxShadow }) => {
        lines.push(`  --${prefix}shadow-${level}: ${boxShadow};`)
      })
    }

    if (includeDropShadow) {
      if (includeBoxShadow) {
        lines.push(``)
      }
      shadows.forEach(({ level, dropShadow }) => {
        const value = dropShadow === "none" ? "none" : dropShadow
        lines.push(`  --${prefix}drop-shadow-${level}: ${value};`)
      })
    }

    lines.push(`}`)
  } else {
    // Class format
    if (includeBoxShadow) {
      lines.push(`/* Box Shadows */`)
      shadows.forEach(({ level, boxShadow }) => {
        lines.push(`.${prefix}shadow-${level} {`)
        lines.push(`  box-shadow: ${boxShadow};`)
        lines.push(`}`)
        lines.push(``)
      })
    }

    if (includeDropShadow) {
      lines.push(`/* Drop Shadows */`)
      shadows.forEach(({ level, dropShadow }) => {
        const value = dropShadow === "none" ? "none" : dropShadow
        lines.push(`.${prefix}drop-shadow-${level} {`)
        lines.push(`  filter: ${value};`)
        lines.push(`}`)
        lines.push(``)
      })
    }
  }

  return lines.join("\n")
}

/**
 * Generates CSS Module content (same as CSS but works with module systems).
 */
export function generateCSSModule(
  preset: ShadowPreset,
  options: GenerateCSSOptions = {}
): string {
  return generateCSS(preset, options)
}
